import React, { useState, useRef, useEffect } from 'react';
import { Share2, FileText, Code2, Copy, Check, ChevronDown } from 'lucide-react';

export default function ExportShare({ result, code }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const h = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, []);

  function copyText() {
    const text = `${result?.name}\n\n${result?.description}\n\nTime: ${result?.time_complexity} | Space: ${result?.space_complexity}\n\nSteps:\n${result?.steps?.map((s,i)=>`${i+1}. ${s.title}\n   ${s.desc}`).join('\n\n')}`;
    navigator.clipboard.writeText(text);
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  }

  function exportPDF() {
    const html = `<html><head><title>${result?.name}</title><style>
    body{font-family:'Segoe UI',sans-serif;max-width:720px;margin:0 auto;padding:40px;color:#09090b;line-height:1.6}
    h1{font-size:24px;font-weight:600;margin-bottom:4px;color:#09090b}
    .meta{display:flex;gap:8px;margin:12px 0;flex-wrap:wrap}
    .badge{padding:3px 10px;border-radius:20px;font-size:12px;font-weight:500}
    .time{background:#fef3c7;color:#92400e}.space{background:#eff6ff;color:#1e40af}.lang{background:#f4f4f5;color:#71717a}
    p{color:#52525b;font-size:14px;margin:12px 0}
    .tip{background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:10px 14px;font-size:13px;color:#78350f;margin:16px 0}
    h2{font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:.05em;color:#a1a1aa;margin:24px 0 10px}
    .step{display:flex;gap:12px;margin-bottom:12px;padding:12px;background:#fafafa;border-radius:8px;border-left:2px solid #14b8a6}
    .num{width:22px;height:22px;background:#14b8a6;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:600;flex-shrink:0}
    .step-title{font-weight:600;font-size:13px;color:#09090b;margin-bottom:3px}
    .step-desc{font-size:12px;color:#71717a}
    .code-ref{font-family:monospace;font-size:11px;background:#f4f4f5;color:#14b8a6;padding:2px 6px;border-radius:4px;margin-top:4px;display:inline-block}
    .code{background:#09090b;color:#f4f4f5;padding:20px;border-radius:10px;font-family:monospace;font-size:12px;white-space:pre-wrap;margin-top:8px}
    .footer{margin-top:40px;padding-top:16px;border-top:1px solid #e4e4e7;text-align:center;font-size:12px;color:#a1a1aa}
    </style></head><body>
    <h1>${result?.name || 'Analysis'}</h1>
    <div class="meta">
      <span class="badge time">Time: ${result?.time_complexity||'N/A'}</span>
      <span class="badge space">Space: ${result?.space_complexity||'N/A'}</span>
      <span class="badge lang">${result?.language||''}</span>
    </div>
    <p>${result?.description||''}</p>
    ${result?.tips?`<div class="tip">💡 ${result.tips}</div>`:''}
    <h2>Step-by-Step Breakdown</h2>
    ${result?.steps?.map((s,i)=>`<div class="step"><div class="num">${i+1}</div><div><div class="step-title">${s.title}</div><div class="step-desc">${s.desc}</div>${s.code_ref?`<div class="code-ref">${s.code_ref}</div>`:''}</div></div>`).join('')||''}
    ${result?.use_cases?.length?`<h2>Use Cases</h2><ul>${result.use_cases.map(u=>`<li style="font-size:13px;color:#71717a;margin-bottom:4px">${u}</li>`).join('')}</ul>`:''}
    <h2>Source Code</h2>
    <div class="code">${(code||'').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</div>
    <div class="footer">Generated by Code2Concept &middot; AI-Powered Algorithm Visualizer</div>
    </body></html>`;
    const w = window.open('','_blank'); w.document.write(html); w.document.close(); w.print();
    setOpen(false);
  }

  function exportJSON() {
    const blob = new Blob([JSON.stringify({code,result},null,2)],{type:'application/json'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href=url; a.download=`${result?.name||'analysis'}.json`; a.click();
    URL.revokeObjectURL(url); setOpen(false);
  }

  if (!result) return null;

  return (
    <div className="relative" ref={ref}>
      <button onClick={() => setOpen(o => !o)}
        className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium transition-all"
        style={{ background: open ? 'var(--bg-muted)' : 'transparent', border: '1px solid var(--border)', color: 'var(--text-muted)' }}>
        <Share2 size={12} /> Export <ChevronDown size={11} />
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-1.5 w-44 rounded-xl shadow-lg overflow-hidden z-20 animate-fade-in"
          style={{ background: 'var(--bg)', border: '1px solid var(--border)' }}>
          <div className="p-1">
            {[
              { icon: FileText, label: 'Export as PDF', action: exportPDF },
              { icon: Code2, label: 'Export as JSON', action: exportJSON },
            ].map(({ icon: Icon, label, action }) => (
              <button key={label} onClick={action}
                className="w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm transition-colors text-left"
                style={{ color: 'var(--text)' }}
                onMouseEnter={e => e.currentTarget.style.background = 'var(--bg-muted)'}
                onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
                <Icon size={13} style={{ color: 'var(--brand)' }} /> {label}
              </button>
            ))}
            <div className="my-1 border-t" style={{ borderColor: 'var(--border)' }} />
            <button onClick={() => { copyText(); setOpen(false); }}
              className="w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm transition-colors"
              style={{ color: 'var(--text)' }}
              onMouseEnter={e => e.currentTarget.style.background = 'var(--bg-muted)'}
              onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
              {copied ? <Check size={13} style={{ color: 'var(--brand)' }} /> : <Copy size={13} style={{ color: 'var(--brand)' }} />}
              {copied ? 'Copied!' : 'Copy analysis'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
